/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NevNative */

#ifndef _Included_NevNative
#define _Included_NevNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NevNative
 * Method:    display
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_NevNative_display
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
